# Generated by Django 4.1 on 2022-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_member_historymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymember',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
