# Generated by Django 4.1 on 2022-08-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_historymember_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymember',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
