# Generated by Django 4.1 on 2022-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_historymember_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymember',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
